### ISSUE TITLE
Fix databuilder docs build

### ISSUE THREAD

**Issue by inglesp** [opensafely/documentation#767]
Following instructions [here](https://docs.opensafely.org/updating-the-docs#updating-data-builder-backend-and-contract-documentation), I've pulled in the latest version of databuilder.  However, the docs no longer build.  See #766 and [this CI run](https://github.com/opensafely/documentation/runs/6715933413?check_suite_focus=true).

The error is:

```
 ERROR    -  Error reading page 'data-backends.md': 'contracts'
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.8.12/x64/bin/mkdocs", line 8, in <module>
    sys.exit(cli())
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/mkdocs/__main__.py", line 192, in build_command
    build.build(config.load_config(**kwargs), dirty=not clean)
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/mkdocs/commands/build.py", line 292, in build
    _populate_page(file.page, config, files, dirty)
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/mkdocs/commands/build.py", line 170, in _populate_page
    page.markdown = config['plugins'].run_event(
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/mkdocs/plugins.py", line 102, in run_event
    result = method(item, **kwargs)
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/plugin/main.py", line 50, in on_page_markdown
    backend = render_backend(data, match)
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/plugin/backends.py", line 20, in render_backend
    (c, c.lower().replace("/", "")) for c in sorted(backend_data["contracts"])
KeyError: 'contracts'
```

**Comment by iaindillingham** [comment]
I think this is because Data Builder's `generate-docs` command is broken. See opensafely-core/databuilder#537 for the fix. I've created a new _public_docs.json_ from this PR, which is committed to #766.

**Comment by iaindillingham** [comment]
opensafely-core/databuilder#537 and opensafely/documentation#766 have been merged, and the docs have been [successfully deployed](https://dashboard.render.com/static/srv-c8ktt8bru51rtre94jsg/deploys/dep-caf06ov9re0guldpmrq0) to Render. As such, I'm going to close this issue.
