### ISSUE TITLE
Dependabot version updates are failing in `databuilder/` directory

### ISSUE THREAD

**Issue by StevenMaude** [opensafely/documentation#807]
```

updater | ERROR <job_392265894> Error processing snex (Dependabot::SharedHelpers::HelperSubprocessFailed)
updater | ERROR <job_392265894> Using indexes:
updater | <job_392265894>   https://pypi.org/simple
updater | <job_392265894> 
updater | <job_392265894>                           ROUND 1                           
updater | <job_392265894> Traceback (most recent call last):
updater | <job_392265894>   File "/usr/local/.pyenv/versions/3.8.12/bin/pip-compile", line 8, in <module>
updater | <job_392265894>     sys.exit(cli())
updater | <job_392265894>   File "/usr/local/.pyenv/versions/3.8.12/lib/python3.8/site-packages/click/core.py", line 1130, in __call__
updater | <job_392265894>     return self.main(*args, **kwargs)
updater | <job_392265894>   File "/usr/local/.pyenv/versions/3.8.12/lib/python3.8/site-packages/click/core.py", line 1055, in main
updater | <job_392265894>     rv = self.invoke(ctx)
updater | <job_392265894>   File "/usr/local/.pyenv/versions/3.8.12/lib/python3.8/site-packages/click/core.py", line 1404, in invoke
updater | <job_392265894>     return ctx.invoke(self.callback, **ctx.params)
updater | <job_392265894>   File "/usr/local/.pyenv/versions/3.8.12/lib/python3.8/site-packages/click/core.py", line 760, in invoke
updater | <job_392265894>     return __callback(*args, **kwargs)
updater | <job_392265894>   File "/usr/local/.pyenv/versions/3.8.12/lib/python3.8/site-packages/click/decorators.py", line 26, in new_func
updater | <job_392265894>     return f(get_current_context(), *args, **kwargs)
updater | <job_392265894>   File "/usr/local/.pyenv/versions/3.8.12/lib/python3.8/site-packages/piptools/scripts/compile.py", line 466, in cli
updater | <job_392265894>     results = resolver.resolve(max_rounds=max_rounds)
updater | <job_392265894>   File "/usr/local/.pyenv/versions/3.8.12/lib/python3.8/site-packages/piptools/resolver.py", line 175, in resolve
updater | <job_392265894>     has_changed, best_matches = self._resolve_one_round()
updater | <job_392265894>   File "/usr/local/.pyenv/versions/3.8.12/lib/python3.8/site-packages/piptools/resolver.py", line 300, in _resolve_one_round
updater | <job_392265894>     constraints = sorted(self.constraints, key=key_from_ireq)
updater | <job_392265894>   File "/usr/local/.pyenv/versions/3.8.12/lib/python3.8/site-packages/piptools/resolver.py", line 133, in constraints
updater | <job_392265894>     return set(
updater | <job_392265894>   File "/usr/local/.pyenv/versions/3.8.12/lib/python3.8/site-packages/piptools/resolver.py", line 280, in _group_constraints
updater | <job_392265894>     sorted(
updater | <job_392265894>   File "/usr/local/.pyenv/versions/3.8.12/lib/python3.8/site-packages/piptools/resolver.py", line 282, in <lambda>
updater | <job_392265894>     key=(lambda x: (key_from_ireq_with_name(x), not x.editable)),
updater | <job_392265894>   File "/usr/local/.pyenv/versions/3.8.12/lib/python3.8/site-packages/piptools/resolver.py", line 273, in key_from_ireq_with_name
updater | <job_392265894>     return key_from_ireq(self._get_ireq_with_name(ireq, cache))
updater | <job_392265894>   File "/usr/local/.pyenv/versions/3.8.12/lib/python3.8/site-packages/piptools/resolver.py", line 237, in _get_ireq_with_name
updater | <job_392265894>     self.repository.get_dependencies(name_proxy)
updater | <job_392265894>   File "/usr/local/.pyenv/versions/3.8.12/lib/python3.8/site-packages/piptools/repositories/local.py", line 79, in get_dependencies
updater | <job_392265894>     return self.repository.get_dependencies(ireq)
updater | <job_392265894>   File "/usr/local/.pyenv/versions/3.8.12/lib/python3.8/site-packages/piptools/repositories/pypi.py", line 247, in get_dependencies
updater | <job_392265894>     self._dependencies_cache[ireq] = self.resolve_reqs(
updater | <job_392265894>   File "/usr/local/.pyenv/versions/3.8.12/lib/python3.8/site-packages/piptools/repositories/pypi.py", line 210, in resolve_reqs
updater | <job_392265894>     results = resolver._resolve_one(reqset, ireq)
updater | <job_392265894>   File "/usr/local/.pyenv/versions/3.8.12/lib/python3.8/site-packages/pip/_internal/resolution/legacy/resolver.py", line 503, in _resolve_one
updater | <job_392265894>     _check_dist_requires_python(
updater | <job_392265894>   File "/usr/local/.pyenv/versions/3.8.12/lib/python3.8/site-packages/pip/_internal/resolution/legacy/resolver.py", line 105, in _check_dist_requires_python
updater | <job_392265894>     raise UnsupportedPythonVersion(
updater | <job_392265894> pip._internal.exceptions.UnsupportedPythonVersion: Package 'opensafely-databuilder' requires a different Python: 3.8.12 not in '>=3.9'
```

**Comment by StevenMaude** [comment]
Relates to #493.
